# Generated by Django 5.0.4 on 2026-03-15 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.UUIDField(unique=True)),
                ('event_name', models.CharField(max_length=255)),
                ('seat', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Ожидает генерации'), ('generated', 'PDF создан'), ('sent', 'Отправлен'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
