# Generated by Django 5.0.4 on 2026-03-15 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('venue', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, verbose_name='Изображение')),
                ('total_seats', models.IntegerField(default=100, verbose_name='Всего мест')),
                ('available_seats', models.IntegerField(default=100, verbose_name='Свободных мест')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sale_open', models.BooleanField(default=False, verbose_name='Продажи открыты')),
                ('sale_open_at', models.DateTimeField(blank=True, null=True, verbose_name='Время открытия продаж')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vip', 'VIP'), ('standard', 'Стандарт'), ('economy', 'Эконом')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('color', models.CharField(default='#6366f1', max_length=20, verbose_name='Цвет на карте')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='events.event')),
            ],
            options={
                'verbose_name': 'Категория мест',
                'verbose_name_plural': 'Категории мест',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=5, verbose_name='Ряд')),
                ('number', models.IntegerField(verbose_name='Номер места')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('status', models.CharField(choices=[('available', 'Свободно'), ('booked', 'Забронировано'), ('sold', 'Продано'), ('blocked', 'Заблокировано')], default='available', max_length=20, verbose_name='Статус')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.event')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='events.seatcategory')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['row', 'number'],
                'unique_together': {('event', 'row', 'number')},
            },
        ),
    ]
